trigger:
- main

pool:
  name: Default  # Tu agente self-hosted

variables:
  MAVEN_OPTS: "-Xmx1024m"
  JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'fecha-festiva-api/pom.xml'
    goals: 'clean install'
    options: '-DskipTests=false'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
  displayName: 'Build & Test with Maven'

- task: CopyFiles@2
  inputs:
    contents: '**/target/*.jar'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy JAR to artifact staging'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish Artifact'
